# Generated by Django 5.2.6 on 2025-09-05 05:43

import apps.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=apps.models.GenRandomUUID(),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="videos/",
                        validators=[
                            django.core.validators.FileExtensionValidator(["mp4"])
                        ],
                    ),
                ),
                ("duration", models.DurationField()),
                (
                    "type",
                    models.CharField(
                        choices=[("public", "Public"), ("private", "Private")],
                        default="public",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "required_db_vendor": "postgresql",
            },
        ),
    ]
